### ISSUE TITLE
李婧仪WBS

### ISSUE THREAD

**Issue by dlutljy** [ylyxf/SECourse#63]
![default](https://cloud.githubusercontent.com/assets/14888659/11057897/0ad4093e-87ca-11e5-94c8-085f61ce6061.png)
![default](https://cloud.githubusercontent.com/assets/14888659/11057904/133a11cc-87ca-11e5-9fc6-e9bbdb8e1b85.png)
![default](https://cloud.githubusercontent.com/assets/14888659/11057909/1a244ff2-87ca-11e5-99a1-0b0ffcbcce53.png)

**Comment by ylyxf** [comment]
校区辩论赛，正式开展没有展开
